services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    # Nome do container
    container_name: api-imersao-devops
    # Mapeia a porta 8000 do host para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual no contêiner para live-reloading
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com uvicorn, habilitando o reload automático
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload